export const environment = {
  production: true,
  replaceChar: ' ',
  urlBaseGS: 'Geo_ANTS',
  urlBase: 'api/v1',
  clientTypeVersion: 'Prod.',
  nomeLogin: 'Luigi.Pecce',
  // pwdLogin: 'cerioni',
  // nomeLogin: 'Luigi.Pecce.29',
  // pwdLogin: 'Lati_01',
  layerPerGraficoNumerico: 'Geo_ANTS:l_geo_measr_num_sample',
  layerPerGraficoStringa: 'Geo_ANTS:l_geo_measr_str_sample',
  layerNumerico: 'Geo_ANTS:l_geo_measr_num_line',
  layerStringa: 'Geo_ANTS:l_geo_measr_str_line',
  // spostamentoMillisecondi: 3600000,
  // spostamentoMillisecondi: 0,
  stringaLatestSelection: '<Latest Selected>',
  stringaAll: '<All>',
  stringaGlobalSettingSLA: '<Global SLA>',
  stringaGlobalSettingMapStyle: '<Global Map Style>',
  stringaClusterGlobale: '<Global Cluster>',
  quantiFrames: 9,
  quantiSottoFrames: 30,
  quantePagine: 30
};
